# Generated by Django 4.2.3 on 2024-02-16 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.URLField(max_length=300)),
                ('comic_geeks_code', models.IntegerField()),
                ('variant', models.BooleanField(default=False)),
                ('cover_artist', models.CharField(max_length=100, null=True)),
                ('arc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comictracker.comic')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComicsToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comictracker.comic')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComicsToSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comictracker.comic')),
                ('volume_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comictracker.series')),
            ],
        ),
    ]
