# Generated by Django 4.2.3 on 2024-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comictracker', '0003_rename_cover_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cgid',
            field=models.IntegerField(default=0),
        ),
    ]
