# Generated by Django 4.2.3 on 2024-02-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comictracker', '0004_series_cgid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicstoseries',
            old_name='volume_key',
            new_name='series_key',
        ),
    ]
