# Generated by Django 4.2.3 on 2024-02-22 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comictracker', '0005_rename_volume_key_comicstoseries_series_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicstouser',
            name='comic_key',
        ),
        migrations.RemoveField(
            model_name='comicstouser',
            name='user_key',
        ),
        migrations.AddField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comictracker.series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ComicsToSeries',
        ),
        migrations.DeleteModel(
            name='ComicsToUser',
        ),
    ]
