# Generated by Django 4.2.3 on 2024-02-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comictracker', '0006_remove_comicstouser_comic_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comictracker.series'),
        ),
    ]
