# Generated by Django 4.2.3 on 2024-02-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comictracker', '0009_alter_comic_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comictracker.artist'),
        ),
    ]
